feat(005): Galery Component
M1409/proposta-germinare pull request #8
Opened 2022-11-10 20:36 UTC by lsjesus

2022-11-15 16:07 UTC, AlexandroMinobe commented
Qual é a função desse componente? O intuito é que seja uma seção da página ou uma galeria?

2022-11-15 16:08 UTC, AlexandroMinobe requested changes

2022-11-15 16:08 UTC, AlexandroMinobe commented on src/Pages/Home/Components/Galery/Galery.tsx
> +                        <img src={ifull_screen} alt="" className={styles.fullScreen}/>
Está faltando o alt.

2022-11-16 18:52 UTC, lsjesus commented
> Está faltando fechar o p. Não tem o componente Typography para ser utilizado? 

Perceba que estou passando um HTML como parâmetro de uma função de uma lib, portanto não tem como eu passar o componente Typography até onde eu sei

2022-11-16 18:59 UTC, merged